baseURL = 'https://tom-howard.github.io/ros/'
canonifyURLs = true
languageCode = 'en-GB'
title = 'ROS Labs at The University of Sheffield'

theme = "hugo-theme-learn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/tom-howard/ros/tree/main/content/"
  author = "Tom Howard"
  description = "Practical lab courses on ROS (the Robot Operating System). Developed by Tom Howard, for teaching activities at The University of Sheffield."
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = false
  disableLandingPageButton = false
  disableLanguageSwitchingButton = true
  disableBreadcrumb = false
  disableNextPrev = true
  ordersectionsby = "weight"
  themeVariant = "blue"
  titleSeparator = "|"
