site_name: "Robotics in the Diamond: ROS"
site_url: https://tom-howard.github.io/ros/
site_description: Practical ROS Courses in The Diamond at The University of Sheffield. 
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  font: false
    # text: Source Sans Pro
    # code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/tuos.png
  favicon: assets/favicon.png

  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  
copyright: >
  Copyright &copy; 2023 The University of Sheffield <br />
  Content by <a href="https://www.sheffield.ac.uk/engineering/diamond-engineering/our-staff/tom-howard">Dr Tom Howard</a> (License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC</a>)<br />
  <a href="#__consent">Change cookie settings</a>
repo_url: https://github.com/tom-howard/ros
repo_name: tom-howard/ros
edit_uri: ./edit/main/docs

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      enabled: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.keys

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: 
      We use cookies to monitor the usage of these resources, and to understand 
      how effective they are in supporting your learning. Cookies also help us to 
      evaluate how much impact our teaching materials are making in the community.
      With your support, you are helping us to make our teaching resources better.
